[package]
name = "wirth"
version = "0.0.1"
authors = ["Pierre-Henri Trivier <phtrivier@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
