##
# Project Title
#
# @file
# @version 0.1

.PHONY: test book

test:
	cargo test

book:
	# TODO(pht) verso the file, recto the file, use pandoc, etc...
	# I lost the book.sh script, I'm so stupid...

# end
